---
- name: "Installing brew taps"
  homebrew_tap: 
    name: "{{ item }}"
    state: present
  with_items: "{{ brew_taps }}"

- name: "Installing brew apps"
  homebrew: 
    name: "{{ brew_apps }}"
    state: present

- name: "Installing from brew cask apps"
  homebrew_cask: 
    name: "{{ item }}"
    state: present
    accept_external_apps: yes
  with_items: "{{ brew_cask_apps }}"

- name: "Installing pip apps"
  pip: 
    name: "{{ item }}"
    state: present
  with_items: "{{ pip_apps }}"