---
java_brew_taps: []
  - adoptopenjdk/openjdk

java_brew_apps: 
  - jenv

java_brew_cask_apps:
  # install from jetbrains toolbox 
  # use CLI when it's available: https://youtrack.jetbrains.com/issue/TBX-653
  #- intellij-idea-ce 
  - adoptopenjdk/openjdk/adoptopenjdk8
  - adoptopenjdk/openjdk/adoptopenjdk11

java_global_version: 
  - 1.8